In [1]:
import pandas as pd
import numpy as np

In [2]:
labels =['a','b','c']
list1=[10,20,30]
a=np.array([10,20,30])
d={'a':10,'b':20,'c':30}
pd.Series(data = list1)

0    10
1    20
2    30
dtype: int64

In [3]:
pd.Series(data = list1,index = labels)

a    10
b    20
c    30
dtype: int64

In [4]:
pd.Series(list1,labels)

a    10
b    20
c    30
dtype: int64

In [5]:
pd.Series(a)

0    10
1    20
2    30
dtype: int64

In [6]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [7]:
pd.Series(a,labels)

a    10
b    20
c    30
dtype: int64

In [8]:
ser1 = pd.Series([10,20,30,40], index = ['apple','mango','grapes','cherry']) 
ser2 = pd.Series([10,30,40,50], index = ['apple','grapes','cherry','kiwi']) 
ser1 +ser2

apple     20.0
cherry    80.0
grapes    60.0
kiwi       NaN
mango      NaN
dtype: float64

In [9]:
ser1["mango"]

np.int64(20)

In [10]:
from numpy.random import randn 
np.random.seed(101)
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split()) 
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [11]:
df['Z']

A    0.503826
B    0.605965
C   -0.589001
D    0.955057
E    0.683509
Name: Z, dtype: float64

In [12]:
df[['Z','X']]

          Z         X
A  0.503826  0.628133
B  0.605965 -0.319318
C -0.589001  0.740122
D  0.955057 -0.758872
E  0.683509  1.978757

In [13]:
df['new'] = df['Z'] + df['W'] 
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.210676
B  0.651118 -0.319318 -0.848077  0.605965  1.257083
C -2.018168  0.740122  0.528813 -0.589001 -2.607169
D  0.188695 -0.758872 -0.933237  0.955057  1.143752
E  0.190794  1.978757  2.605967  0.683509  0.874303

In [14]:
df.drop(columns ='new',axis=1)

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [15]:
df.drop(columns ='new')

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [16]:
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.210676
B  0.651118 -0.319318 -0.848077  0.605965  1.257083
C -2.018168  0.740122  0.528813 -0.589001 -2.607169
D  0.188695 -0.758872 -0.933237  0.955057  1.143752
E  0.190794  1.978757  2.605967  0.683509  0.874303

In [17]:
df.drop(columns ='new',axis = 1,inplace=True)
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [18]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [19]:
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [20]:
df.iloc[2]

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

In [21]:
df.loc['A','Y']

np.float64(0.9079694464765431)

In [22]:
df.loc[['A','B'],['X','Y']]

          X         Y
A  0.628133  0.907969
B -0.319318 -0.848077

In [23]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [24]:
df>0

       W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [25]:
df[df>0]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [27]:
df[df['W']>0]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [28]:
df['W']>0

A     True
B     True
C    False
D     True
E     True
Name: W, dtype: bool

In [29]:
df[df['W']>0] ['Y']

A    0.907969
B   -0.848077
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [30]:
df[df['W']>0][['X','Y']]

          X         Y
A  0.628133  0.907969
B -0.319318 -0.848077
D -0.758872 -0.933237
E  1.978757  2.605967

In [31]:
df[(df['W']>0) & (df['Y']>1)]

          W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [43]:
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[44,55,66,44],'col3': ['abc','def','ghi','xyz']})
df.head()

   col1  col2 col3
0     1    44  abc
1     2    55  def
2     3    66  ghi
3     4    44  xyz

In [44]:
df['col2'].unique()

array([44, 55, 66])

In [45]:
df['col3'].nunique()

4

In [46]:
df['col3'].value_counts()

col3
abc    1
def    1
ghi    1
xyz    1
Name: count, dtype: int64

In [48]:
newdf= df[(df['col1']>2) & (df['col2']==44)] 
newdf

   col1  col2 col3
3     4    44  xyz

In [49]:
def times2(x):  
    return x*2
df['col1'].apply(times2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [50]:
df['col3'].apply(len)

0    3
1    3
2    3
3    3
Name: col3, dtype: int64

In [51]:
df['col1'].sum()

np.int64(10)

In [53]:
del df['col1']
df

   col2 col3
0    44  abc
1    55  def
2    66  ghi
3    44  xyz

In [55]:
df.columns
Index(['col2', 'col3'], dtype='object') 
df.Index 
RangeIndex(start=0, stop=4, step=1)

NameError: name 'Index' is not defined

In [56]:
df.sort_values(by='col2')

   col2 col3
0    44  abc
3    44  xyz
1    55  def
2    66  ghi

In [58]:
df.sort_values(by='col2', inplace = True)
df

   col2 col3
0    44  abc
3    44  xyz
1    55  def
2    66  ghi

In [59]:
df.isnull()

    col2   col3
0  False  False
3  False  False
1  False  False
2  False  False

In [61]:
import pandas as pd 
import numpy as np

In [63]:
df=pd.read_csv('/home/oem/Downloads/Salaries.csv') 
df

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]

In [64]:
df.head()

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000
2  Prof          A   23       20  Male  110515
3  Prof          A   40       31  Male  131205
4  Prof          B   20       18  Male  104800

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   rank        78 non-null     object
 1   discipline  78 non-null     object
 2   phd         78 non-null     int64
 3   service     78 non-null     int64
 4   sex         78 non-null     object
 5   salary      78 non-null     int64
dtypes: int64(3), object(3)
memory usage: 3.8+ KB

In [67]:
df['phd'].mean()

np.float64(19.705128205128204)

In [69]:
df['service'].max()

np.int64(51)

In [70]:
df[df['phd']==56]['service']

0    49
Name: service, dtype: int64

In [73]:
df['salary'][df['rank']=='AssocProf']

6      81285
30    107008
34    119800
41     74830
47    103613
54     62884
56     77500
59    103994
61    103750
62    109650
64     73300
71     71065
74    104542
Name: salary, dtype: int64

In [74]:
df[df['salary'].max()==df['salary']]

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960

In [75]:
df[df['salary'].min()==df['salary']]

   rank discipline  phd  service   sex  salary
9  Prof          A   51       51  Male   57800

In [76]:
df.groupby('rank')['salary'].mean()

rank
AssocProf     91786.230769
AsstProf      81362.789474
Prof         123624.804348
Name: salary, dtype: float64

In [78]:
df['service'].nunique()

33

In [79]:
df['rank'].value_counts().head()

rank
Prof         46
AsstProf     19
AssocProf    13
Name: count, dtype: int64

In [80]:
df['rank'].apply(lambda str:
('salary' in str.lower())).sum()

np.int64(0)

In [81]:
(df[df['phd']==2013]
['service'].value_counts()==1).sum()

np.int64(0)

In [82]:
def find_chief(rank):  
    if 'prof' in rank.lower().split(): 
        return True 
    else:
        return False

In [83]:
sum(df['rank'].apply(lambda x: 
find_chief(x)))

46